package ru.nsu.bolotov.model.filter.mode;

public enum FilterMode {
    IDENTITY,
    WHITE_AND_BLACK,
    NEGATIVE,
    GAUSS_SMOOTHING,
    SHARPNESS_INCREASING,
    EMBOSSING,
    GAMMA_CORRECTION,
    ROBERTS_OPERATOR,
    SOBEL_OPERATOR,
    FLOYD_STEINBERG_DITHERING,
    ORDERLY_DITHERING,
    AQUA_REALIZATION,
    ROTATE,
    RETRO_EFFECT
}
