package ru.nsu.bolotov.model.mode;

public enum FilterMode {
    CHANGE_VIEW_MODE,
    WHITE_AND_BLACK,
    NEGATIVE,
    GAUSS_SMOOTHING,
    SHARPNESS_INCREASING,
    EMBOSSING,
    GAMMA_CORRECTION,
    ROBERTS_OPERATOR,
    SOBEL_OPERATOR,
    FLOYD_STEINBERG_DITHERING,
    ORDERLY_DITHERING
}
